<?php

use Illuminate\Database\Seeder;
use Faker\Factory as Faker;

class PhraseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $frases = ["Francia, Suiza y Hungría ya hicieron causa común.",
        "Mi primer profesor de lengua fue López García.",
        "Guillermo y Yolanda practicaban ciclismo con Jaime.",
        "El primero en Guipúzcoa y el segundo en Valladolid.",
        "Fue aquel hombre tan gordo el que se acercó en globo.",
        "éramos un grupo de profesores de lengua y literatura.",
        "Yo no recuerdo en mi pueblo ningún caso de triquinosis.",
        "éramos un grupo de gente bastante distinguida.",
        "Después ya se hizo muy amiga nuestra.",
        "Los achaques de Jesús remitieron sin causar disgustos.",
        "Su viuda se casó con un profesor de inglés de allá.",
        "Durante tus estudios has hecho algún viaje.",
        "Dos años y medio en Vilanova ya fueron suficientes.",
        "Pero en el fondo le tengo cariño.",
        "Puede haber deficiencia de agua en Logroño.",
        "La sangre se revuelve con estas migas de pan blanco.",
        "Los yernos de Ismael no engordarán los pollos con hierba.",
        "Mi mujer es profesora de Lengua y Literatura.",
        "Sabía un poquito de inglés pero muy poco.",
        "En Julio hacíamos en Burgos otra vez la preparación.",
        "Un niño muy rico que se llama Ignacio.",
        "No en lenguaje hablado pero sí en lenguaje escrito.",
        "Era muy gordo, muy gordo y con un tupé inmenso.",
        "Ellos, ya desde un principio, se quedan con el dinero.",
        "Después de la mili ya me vine a Cataluña.",
        "Estuve en Guernica dando clase de lengua y literatura.",
        "Firmaban como cántabros incluso en tumbas funerarias.",
        "Aunque ellos ya engrasaron los ejes como yo les enseñé.",
        "Habla un poco de su prepotencia y de su orgullo.",
        "Trabajaba en Granollers y vivía en Barcelona.",
        "Es uno de los recuerdos más bonitos que guardo.",
        "Vimos que el ambiente había cambiado mucho.",
        "Bajamos un día al mercadillo de Palma.",
        "Por las noches organizaban bailes y fiestas.",
        "Yo entré en filas a cumplir el servicio militar.",
        "Uno llevaba el chorizo, el otro llevaba el gazpacho.",
        "Con Gema y con Blanca me veo por las noches en casa.",
        "Subimos un rato al apartamento y luego ya nos fuimos.",
        "Le voy a contar por qué he estudiado lengua.",
        "Llevas quince años fuera de la montaña.",
        "Existe un viento del norte que es un viento frío.",
        "Nos dio el disgusto más grande de nuestra vida.",
        "Se hacen chorizos y salchichones de dos clases.",
        "Antes de primero de bachiller ya te traumatizaban.",
        "La profesora que tengo tampoco es muy agradable.",
        "Yo tengo derecho a que a mí se me entienda.",
        "Al segundo día empezaron a llegar colegios.",
        "En estos pueblos preciosos de Vizcaya y Guipúzcoa.",
        "Me he tomado un café con leche en un bar.",
        "Dentro de muy poco pues va a estar la mitad cubierto.",
        "Los automóviles circulan por el pueblo.",
        "Hay dos niños o tres que le habían dicho que les gustaba.",
        "Cuando entré en el instituto jugué un año más.",
        "Cuéntame los sitios en que has vivido en Cataluña.",
        "Se limpian con agua caliente y raspándolos bien.",
        "Durante el año era muchísimo más barato.",
        "Yo he visto a gente expulsarla del colegio por fumar.",
        "A las ocho de la mañana ya estaba haciendo guardia.",
        "Nos lo pasamos muy bien aunque no vimos nada.",
        "Nos cogieron y nos llevaron otra vez al congreso.",
        "En Nochevieja, de los cincuenta, sólo cinco íbamos a casa.",
        "Pero a las pequeñas les falta todavía aprender mucho.",
        "Con veintiún años podrías comenzar a comerte el mundo.",
        "Sus calles son empedradas y los faroles de hierro viejo.",
        "Guadalajara no está colgada de las rocas. Cuenca sí.",
        "En diez minutos te puedes colocar en Peñacabarga.",
        "Iba vestida muy rara pero era superdivertida.",
        "Como es lógico donde hay montañas hay valles.",
        "A Belén la conocí cuando hice primero el primer curso.",
        "De repente se giró una cosa con gafas y era Carlos.",
        "No se hablaba de ella en ningún noticiero.",
        "Al final llegamos corriendo por la carretera.",
        "Pasé un año dando clase aquí, en Bellaterra.",
        "Ya empezarán los malos modos o los morritos.",
        "El año pasado no pude porque cambié de trabajo.",
        "Yo iba hasta la ermita de San Gabriel con este cacharro.",
        "Yo tuve la suerte de que había unas conferencias.",
        "El carácter es en principio cerrado aunque luego se da.",
        "Una vez que ya se ha chocarrado bien se limpia la piel.",
        "Los mandos nos hacían la vida imposible.",
        "Pero tú ahora elijes ya previamente.",
        "Empezamos a reivindicar que se hiciese pueblo nuevo.",
        "Nosotros esto lo tuvimos muy claro desde el principio.",
        "Lo han tirado abajo y han hecho un bloque nuevo.",
        "Entonces todo el mundo vive de la agricultura.",
        "Yo me quedé con tu amiga Gloria casi toda la noche.",
        "Estuve una semana allí en Cataluña.",
        "Rita ha desayunado mientras yo me afeitaba.",
        "Les dijeron que eligieran una casa allá, en las mismas condiciones.",
        "Podríamos encasillarlo como hombre de derechas.",
        "Los hombres normalmente chocarran el cochino.",
        "Yo me he dado cuenta cuando he vuelto aquí.",
        "Pajares está a cinco kilómetros de San Andrés.",
        "Yo creo que Víctor habló con los franceses en una pausa del congreso.",
        "Ganamos todos los partidos menos el de la final.",
        "Conseguimos que se hiciese un pueblo.",
        "Cuando me giré ya no tenía la cartera.",
        "Los servicios que pueden prestar son muy superiores.",
        "Esos años estuvimos haciendo ocho asignaturas.",
        "Había un autobús que nos llevaba otra vez para el cuartel.",
        "Es la riqueza ganadera y la riqueza agrícola.",
        "Había algunos que no habían visto nunca el mar.",
        "Por otra parte es una ciudad que está muy cuidada.",
        "Tiene quince y está haciendo primero de BUP.",
        "Tendrá unas siete u ocho islas alrededor.",
        "Son los cuadros más bonitos de las casas de mi pueblo.",
        "Un partido socialista con representatividad.",
        "Produce dolor de cabeza a los montañeses.",
        "Una para ellos y otra para invitar a las chicas.",
        "Es un hombre franco pero no es un hombre que se entregue.",
        "Desde esta perspectiva han de ser dos culturas.",
        "Van a echar abajo la tribuna para aumentar su capacidad.",
        "Haciendo el primer campamento y el segundo campamento.",
        "A aquella gente que le va mucho la vida militar.",
        "Por otra parte, yo estaba fuera de mi casa.",
        "Hoy no tenía que llevar bocadillo por la mañana.",
        "Pero yo quería ser ingeniero de montes.",
        "No se hace en ningún sitio como se hace allá.",
        "Un matrimonio ya mayor manda a su hijo a Alicante.",
        "Recibíamos un nombre que es los foramontanos.",
        "Unas indemnizaciones no les iban del todo mal.",
        "Las de dos pisos tienen un primer piso con una habitación.",
        "Nos íbamos preparando con aquellos equipos tan gloriosos.",
        "Había gente que quería marcharse a vivir a Lumbreras.",
        "Y en el segundo piso, pues hay tres habitaciones.",
        "Me vine aquí y me admitieron en su organización.",
        "En el siglo octavo hizo expulsar a los judíos de España.",
        "Se va dando vueltas a la sangre para que no se cuaje.",
        "Rezando porque tenía un miedo impresionante.",
        "Es uno de los momentos más bonitos del día.",
        "La mitad va a estar cubierto por un pantano.",
        "Los chorizos y los jamones están colgando de las paredes.",
        "El que llevaba todo el club no me caía muy bien.",
        "Nos fuimos a las siete de la mañana y volvimos por la noche.",
        "Lo tengo asociado al día de la matanza.",
        "Hechos con la carne más ensangrentada y más grasienta.",
        "Es un apellido muy abundante en la zona de Pamplona.",
        "Había estado en una tertulia en Logroño.",
        "Y mi padre es de aquí y no es tan bueno.",
        "Volvemos otra vez por encima de Santander.",
        "El mar Atlántico entra por el golfo de Vizcaya.",
        "Yo llevaba la cartera con todo el dinero.",
        "Había mucha gente fuera y nos quedamos sentadas.",
        "En definitiva yo pienso que el pantano está bien.",
        "No jugábamos a básket, sólo los mirábamos a ellos.",
        "Es un sótano que tendrá diez metros de altitud.",
        "Entonces se creó una cuña natural que fue Santander.",
        "Quien mandaba era un alférez que era compañero.",
        "Ganaban el dinero para hacer el viaje.",
        "Bueno, total que va y resulta que me admiten.",
        "Esto se hace cuando ya se saben los resultados del veterinario.",
        "A las ocho y media o así nos volvieron a bajar.",
        "Aunque naturalmente hay un partido comunista.",
        "Casi haciendo frontera con Bilbao está el río Asón.",
        "La mayoría de los guerreros tenían reuma.",
        "Al llegar a Barcelona tendremos que arreglarlo todo.",
        "Esta es una de las cosas que yo más recuerdo.",
        "Acabaron las maniobras éstas de submarinismo.",
        "Esa sangre después se echa en una caldera.",
        "Teníamos que andar unos diez minutos o así.",
        "Dio la casualidad que a la una y media estaban allí.",
        "Llegaba a Santander a las ocho de la mañana.",
        "Se la conoce o la conocen como la pequeña Suiza.",
        "El rey mandó a su yerno a derrotar a los cántabros.",
        "Tiene una niña de dos años que se llama Carmen.",
        "Era como una pequeña cabaña llena de italianos.",
        "Los cochinos estaban bien, no tenían triquinosis.",
        "Se emplea para atar los haces de hierba.",
        "Se alegraron mucho de vernos y ya nos quedamos a cenar.",
        "Bueno, es otra vida completamente distinta.",
        "En el caso mío, yo era delineante industrial.",
        "Esto es por todo el reglamento del mercado común europeo.",
        "Entonces yo había alquilado una hamaca.",
        "Luego Susana se quedó en la bañera con la falda puesta.",
        "Una vez que se cuelga el cochino se deja que se seque.",
        "Uno de esos caciques era amigo de Azaña.",
        "Ya empezamos a llorar bastante en el apartamento.",
        "Le he dado un beso y me he vuelto a mi casa.",
        "Los niños son catalanes, han nacido en Blanes los tres.",
        "No se carga a nadie, es bastante cariñosa.",
        "Teníamos que pasar por unos puntos marcados en el mapa.",
        "La montaña con sus acantilados llega hasta el mar.",
        "Te voy a contar el viaje que he hecho esta mañana.",
        "Es la sede de la actual Universidad Menéndez Pelayo.",
        "En una ladera del monte se ubica la iglesia.",
        "Esto es lo que has hecho durante el año y durante el verano.",
        "Bueno, pero vamos a la historia que te contaba.",
        "La higiene que había allí era bastante deprimente.",
        "Este viento quemó toda la ciudad absolutamente.",
        "Había una especie de montaña o de colina.",
        "Me parece admirable su actitud en este caso.",
        "La carne mala se llama la carne ensangrentada.",
        "Entonces lo único que hacíamos era ir a cenar.",
        "No dormimos prácticamente en toda la noche.",
        "En todos los sitios había italianos.",
        "Tiene espectáculos bastante agradables en verano.",
        "Para ser Semana Santa había mucha gente.",
        "Esta vez no me había preparado en absoluto.",
        "Teníamos permiso para ir a nuestras casas.",
        "Lo que se consigue de esta manera es que todos paguen la cuota.",
        ];
        $faker = Faker::create();
         for ($i=0; $i < count($frases)-1; $i++) {
               \DB::table("list_phrases")->insert(
                     array(
                           'phrase'       => $frases[$i],                           
                           'created_at'   => date('Y-m-d H:m:s'),
                           'updated_at'   => date('Y-m-d H:m:s'),
                           'treatment_id' => 1,
                     )
               );
         }
    }
}