---

stages:
  - deploy
  - composer

deploy:
  stage: deploy
  tags:
   - apituvoz
  script:
   - echo "${CI_COMMIT_REF_NAME}"    
  when: always  
  only: 
    - master 

composer:
  stage: composer
  tags:
   - apituvoz
  script:
   - echo "${CI_COMMIT_REF_NAME}"
  when: always  
  only: 
    - master 