on: 
  push:
    branches:
    - ci/cd
name: deploy API tuVoz
jobs:
  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    strategy:
     matrix:
       php: [7.3]
    steps:
    - uses: actions/checkout@master
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
   
    - name: Cache PHP dependencies
      uses: actions/cache@v1
      with:
        path: vendor
        key: dependencies-php-composer-${{ hashFiles('**/composer.lock') }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.3
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
        coverage: none

    - name: Install dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

    - name: Copy env file
      run: cp .env.example .env
    
    - name: Generate key
      run: php artisan key:generate


    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        pull: true
        tags: fjvigil/api_tuvoz:${{ github.sha }}
