on: 
  push:
    branches:
    - ci/cd
    - master
name: deploy API tuVoz
jobs:
  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    strategy:
     matrix:
       php: [7.3]
    steps:
    - uses: actions/checkout@master
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
   
    - name: Cache PHP dependencies
      uses: actions/cache@v1
      with:
        path: vendor
        key: dependencies-php-composer-${{ hashFiles('**/composer.lock') }}

    - name: Setup PHP${{ matrix.php }} sample
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: deployer
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, pdo_mysql, mysql, soap, intl, json, openssl, xml
        ini-values: post_max_size=512M, max_execution_time=180, memory_limit = 128M 
        coverage: xdebug2

    - name: Install dependencies
      run: |
        composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
        sudo apt-get update && sudo apt-get install php7.3-mcrypt php7.3-xml php7.3-gd php7.3-opcache php7.3-mbstring  php7.3-intl php7.3-bcmath php7.3-common php7.3-json openssl php7.3-curl  

    - name: Copy env file
      run: cp .env.example .env

    - name: Generate key
      run: php artisan key:generate

    - name: storage
      run: chmod -R 777 storage

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        pull: true
        tags: fjvigil/api_tuvoz:${{ github.sha }}

    - name: Build latest 
      if: github.ref == 'refs/heads/master'
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        pull: true
        tags: fjvigil/api_tuvoz
          